# Fastfile with full Loop automation

default_platform(:ios)

TEAMID = ENV["TEAMID"]
GH_PAT = ENV["GH_PAT"]
GITHUB_WORKSPACE = ENV["GITHUB_WORKSPACE"]
GITHUB_REPOSITORY_OWNER = ENV["GITHUB_REPOSITORY_OWNER"]
FASTLANE_KEY_ID = ENV["FASTLANE_KEY_ID"]
FASTLANE_ISSUER_ID = ENV["FASTLANE_ISSUER_ID"]
FASTLANE_KEY = ENV["FASTLANE_KEY"]
DEVICE_NAME = ENV["DEVICE_NAME"]
DEVICE_ID = ENV["DEVICE_ID"]
FASTLANE_USER = ENV["FASTLANE_USER"]
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

platform :ios do
  desc "Provision Identifiers and Certificates"
  lane :identifiers do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = false.to_s

    app_store_connect_api_key(
      key_id: FASTLANE_KEY_ID,
      issuer_id: FASTLANE_ISSUER_ID,
      key_content: FASTLANE_KEY
    )

    def configure_bundle_id(name, identifier, capabilities)
      puts "\n🔧 Configuring bundle ID: #{identifier}"
      bundle_id = Spaceship::ConnectAPI::BundleId.find(identifier)
      if bundle_id.nil?
        puts "📦 Creating new bundle ID: #{identifier}"
        bundle_id = Spaceship::ConnectAPI::BundleId.create(name: name, identifier: identifier)
      else
        puts "📦 Found existing bundle ID: #{identifier}"
      end

      capabilities.each do |capability|
        begin
          bundle_id.create_capability(capability_type: capability)
          puts "✅ Enabled capability #{capability} for #{identifier}"
        rescue => e
          puts "❌ Failed to enable capability #{capability} for #{identifier}: #{e.message}"
        end
      end
    end

    configure_bundle_id("Loop", "com.#{TEAMID}.loopkit.Loop", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS,
      Spaceship::ConnectAPI::BundleIdCapability::Type::HEALTHKIT,
      Spaceship::ConnectAPI::BundleIdCapability::Type::PUSH_NOTIFICATIONS,
      Spaceship::ConnectAPI::BundleIdCapability::Type::SIRIKIT,
      Spaceship::ConnectAPI::BundleIdCapability::Type::USERNOTIFICATIONS_TIMESENSITIVE,
      Spaceship::ConnectAPI::BundleIdCapability::Type::NFC_TAG_READING
    ])

    configure_bundle_id("Loop Intent Extension", "com.#{TEAMID}.loopkit.Loop.Loop-Intent-Extension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

    configure_bundle_id("Loop Status Extension", "com.#{TEAMID}.loopkit.Loop.statuswidget", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])

    configure_bundle_id("WatchApp", "com.#{TEAMID}.loopkit.Loop.LoopWatch", [])

    configure_bundle_id("WatchApp Extension", "com.#{TEAMID}.loopkit.Loop.LoopWatch.watchkitextension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::HEALTHKIT,
      Spaceship::ConnectAPI::BundleIdCapability::Type::SIRIKIT
    ])

    configure_bundle_id("Loop Widget Extension", "com.#{TEAMID}.loopkit.Loop.LoopWidgetExtension", [
      Spaceship::ConnectAPI::BundleIdCapability::Type::APP_GROUPS
    ])
  end

  desc "Check Certificates and Trigger Workflow for Expired or Missing Certificates"
  lane :check_and_renew_certificates do
    setup_ci if ENV['CI']
    ENV["MATCH_READONLY"] = false.to_s

    app_store_connect_api_key(
      key_id: FASTLANE_KEY_ID,
      issuer_id: FASTLANE_ISSUER_ID,
      key_content: FASTLANE_KEY
    )

    new_certificate_needed = false

    certificates = Spaceship::ConnectAPI::Certificate.all
    distribution_certs = certificates.select { |cert| cert.certificate_type == "DISTRIBUTION" }

    if distribution_certs.empty?
      puts "No Distribution certificates found! Triggering action to create certificate."
      new_certificate_needed = true
    else
      distribution_certs.each do |cert|
        expiration_date = Time.parse(cert.expiration_date)
        puts "Current Distribution Certificate: #{cert.id}, Expiration date: #{expiration_date}"
        if expiration_date < Time.now
          puts "Distribution Certificate #{cert.id} is expired!"
          new_certificate_needed = true
        else
          puts "Distribution certificate #{cert.id} is valid. No action required."
        end
      end
    end

    Dir.mkdir("fastlane") unless Dir.exist?("fastlane")
    file_path = File.expand_path("fastlane/new_certificate_needed.txt")
    File.write(file_path, new_certificate_needed ? 'true' : 'false')

    puts ""
    puts "Wrote to new_certificate_needed.txt: #{new_certificate_needed}"
  end

  desc "Create or renew provisioning profiles and distribution certificate"
  lane :certs do
    raise "❌ FASTLANE_USER environment variable is not set. Please add it as a GitHub secret." if FASTLANE_USER.nil?

    setup_ci if ENV['CI']
    match(
      type: "appstore",
      readonly: false,
      force_for_new_devices: true,
      username: FASTLANE_USER
    )
  end

  desc "Nuke and recreate distribution certificates and provisioning profiles"
  lane :nuke_certs do
    raise "❌ FASTLANE_USER environment variable is not set. Please add it as a GitHub secret." if FASTLANE_USER.nil?

    setup_ci if ENV['CI']
    match(type: "appstore", readonly: false, force: true, nuke: true, username: FASTLANE_USER)
    match(type: "appstore", readonly: false, username: FASTLANE_USER)
  end

  desc "Build the Loop app"
  lane :build_loop do
    raise "❌ FASTLANE_USER environment variable is not set. Please add it as a GitHub secret." if FASTLANE_USER.nil?

    setup_ci if ENV['CI']
    match(
      type: "appstore",
      readonly: false,
      username: FASTLANE_USER
    )
    build_app(
      scheme: "Loop",
      export_method: "app-store",
      clean: true,
      output_directory: "./build"
    )
  end
end
